# Generated by Django 5.1.5 on 2025-01-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=100)),
                ('imagem', models.ImageField(upload_to='thumb_img')),
                ('categoria', models.CharField(choices=[('roupas', 'Roupas'), ('calcados', 'Calçados'), ('livros', 'Livros'), ('games', 'Games'), ('celulares', 'Celulares'), ('informática', 'Informática'), ('moveis', 'Móveis')], max_length=30)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('vendido', models.BooleanField(default=False)),
            ],
        ),
    ]
