# Generated by Django 5.1.5 on 2025-01-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('categoria_roupa', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria_produto',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produto.categoria'),
            preserve_default=False,
        ),
    ]
