# Generated by Django 5.1.5 on 2025-01-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_categoria_remove_produto_categoria_produto_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('roupas', 'Roupas'), ('calcados', 'Calçados'), ('livros', 'Livros'), ('games', 'Games'), ('celulares', 'Celulares'), ('informática', 'Informática'), ('moveis', 'Móveis')], default=2, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('pp', 'PP'), ('P', 'P'), ('m', 'M'), ('g', 'G'), ('gg', 'GG')], max_length=30),
        ),
        migrations.AlterField(
            model_name='produto',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
