# Generated by Django 5.1.5 on 2025-01-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_produto_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=4, max_digits=100),
        ),
    ]
